// History: Apr 21 14 tcolar Creation

package main

import (
	"flag"
	"log"

	"github.com/tcolar/album"
)

func main() {

	port := flag.Int("port", 3000, "Web service port")
	password := flag.String("password", "", "Admin password (Otherwise autogenerated)")

	flag.Parse()

	if len(flag.Args()) < 1 {
		log.Fatal("Expected album directory as first parameter.")
	}

	conf := album.AlbumConfig{
		AlbumDir:      flag.Args()[0],
		Port:          *port,
		AdminPassword: *password,
		MediaSizes:    album.StdAlbumSizes,
	}
	// TODO: Relative path db
	store, err := album.NewKvStorer("/tmp/album_db")
	if err != nil {
		log.Fatalf("Failed to open db. %v", err)
	}
	s := album.NewServer(&conf, store)
	s.Run()
}
